site_name: "StateForward"
watch: [ ../stateforward_python, docs ]

theme:
  name: material
  logo: assets/logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.highlight
    - search.suggest
    - toc.follow

  palette:
    scheme: slate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [ !relative $config_dir ]
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
#  - toc:
#      permalink: "¤"

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [ ../stateforward_python ]
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: table
          filters: [ "!^_" ]
          inherited_members: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_root_toc_entry: true
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
